### PR TITLE
Add ShadeGAN and GOF

### PR DESCRIPTION
**Pull request by XingangPan**
Two papers are added: ShadeGAN (https://arxiv.org/abs/2110.15678) and GOF (https://arxiv.org/abs/2111.00969).

### CODE REVIEW

**Comment by XingangPan** [comment]
Hi, is there any chance of merging this pull request? :-)

**Comment by andybak** [comment]
Hi. I've just joined to help maintain the list. Any chance of resubmitting this as there's now conflicts.

**Comment by XingangPan** [comment]
Hi, thanks for helping maintain the list. I just resolved the conflict. Please let me know if there are any further questions.

**Comment by andybak** [comment]
Thanks!

**Pull request merged**
